name: build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: env
        run: env | sort
      - uses: actions/checkout@v3
      - name: run tests
        run: ./run_test.sh
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            webradio.deb
        
